### ISSUE TITLE
Home Assistant 2025.5 : Becker will stop working

### ISSUE THREAD

**Issue by funjuju** [RainerStaude/hass-becker-component-plus-pybecker#57]
Hello,

 I just found in log that message : 

`Enregistreur: homeassistant.helpers.frame
Source: helpers/frame.py:324
S'est produit pour la première fois: 09:41:31 (1 occurrences)
Dernier enregistrement: 09:41:31

Detected that custom integration 'becker' accesses hass.helpers.dispatcher, which should be updated to import functions used from dispatcher directly at custom_components/becker/rf_device.py, line 103: hass.helpers.dispatcher.dispatcher_send(f"{DOMAIN}.{RECEIVE_MESSAGE}", packet). This will stop working in Home Assistant 2025.5, please report it to the author of the 'becker' custom integration`

**Comment by StartDustTC** [comment]
I have the same issue and can confirm, that after updating core to 2024.12.5 the Becker integration stopped working.

**Comment by RainerStaude** [comment]
Please use latest release [v0 3.5](https://github.com/RainerStaude/hass-becker-component-plus-pybecker/releases/tag/v0.3.5)

**Comment by funjuju** [comment]
I'm already on last release V0.3.5 

> I have the same issue and can confirm, that after updating core to 2024.12.5 the Becker integration stopped working.

I'm in 2024.12.5 and tha integration works fine at the moment.

**Comment by RainerStaude** [comment]
Do you still see any warnings in the log?
I updated my setup today and I don't see anything in the log.
The issue you describe above is fixed with release v0.3.5

**Comment by funjuju** [comment]
That's weird, i started my integration fews days ago with the last version and never update it ... i can't see the warning anymore in the logs .. 

sorry for the incovenience :/

**Comment by StartDustTC** [comment]
This is strange, as I restarted Homeassistant several times yesterday, without any change.
I don't know why, but I finally re-downloaded the latest release (v0.3.5) today, then restarted Homeassistant again, and now it's working again. However, all covers were stated in wrong positions. After sending the command to open to each of them, they properly reset their position, and now it seems to work fine again.
Maybe this will help someone with the same issue.

**Comment by RainerStaude** [comment]
To track the state of your cover, you need to setup at least two things:
- Add the travel time to configuration
- Track the cover commands from Becker remotes

```yaml
cover:
  - platform: becker
    covers:
      living_room:
        friendly_name: "Living room Cover"
        channel: "2:1"
        # Determine the movement time in seconds for each cover from closed to open position. 
        # To improve the precision, add the movement time from open to closed position as well
        travelling_time_up: 30
        travelling_time_down: 26.5
        # The remote ID consists of the unit_id and the channel separated by a colon
        # Multiple ID's separated by comma are possible
        # In order to determine the remote ID, it es necessary to enable debug log messages 
        remote_id: "12345:2"
```
Please see [README](https://github.com/RainerStaude/hass-becker-component-plus-pybecker/blob/main/README.md)for more details

**Comment by funjuju** [comment]
Weird thing again : I can see the same message in newer logs : 

Enregistreur: homeassistant.helpers.frame
Source: helpers/frame.py:324
S'est produit pour la première fois: 30 décembre 2024 à 20:17:19 (1 occurrences)
Dernier enregistrement: 30 décembre 2024 à 20:17:19

Detected that custom integration 'becker' accesses hass.helpers.dispatcher, which should be updated to import functions used from dispatcher directly at custom_components/becker/rf_device.py, line 103: hass.helpers.dispatcher.dispatcher_send(f"{DOMAIN}.{RECEIVE_MESSAGE}", packet). This will stop working in Home Assistant 2025.5, please report it to the author of the 'becker' custom integration

**Comment by jandusek4** [comment]
I se it now
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 18:51:45 (1 occurrences)
Last logged: 18:51:45

Detected that custom integration 'becker' accesses hass.helpers.dispatcher, which should be updated to import functions used from dispatcher directly at custom_components/becker/rf_device.py, line 103: hass.helpers.dispatcher.dispatcher_send(f"{DOMAIN}.{RECEIVE_MESSAGE}", packet). This will stop working in Home Assistant 2025.5, please report it to the author of the 'becker' custom integration
```

**Comment by Neverminda** [comment]
This is the error the integration is throwing after I updated to 2025.5


`
2025-05-08 17:36:56.784 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/config/custom_components/becker/pybecker/becker_helper.py", line 234, in run
    self._parse()
    ~~~~~~~~~~~^^
  File "/config/custom_components/becker/pybecker/becker_helper.py", line 262, in _parse
    self._callback(data)
    ~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/becker/rf_device.py", line 64, in <lambda>
    callback = lambda packet: cls.callback(hass, packet)
                              ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/becker/rf_device.py", line 103, in callback
    hass.helpers.dispatcher.dispatcher_send(f"{DOMAIN}.{RECEIVE_MESSAGE}", packet)
    ^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'helpers'
`

**Comment by thomaskonrad** [comment]
I'm getting the same since 2025.5 @RainerStaude. It works a few minutes, then when I want to control a shutter, it throws this exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/config/custom_components/becker/pybecker/becker_helper.py", line 234, in run
    self._parse()
    ~~~~~~~~~~~^^
  File "/config/custom_components/becker/pybecker/becker_helper.py", line 262, in _parse
    self._callback(data)
    ~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/becker/rf_device.py", line 64, in <lambda>
    callback = lambda packet: cls.callback(hass, packet)
                              ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/becker/rf_device.py", line 103, in callback
    hass.helpers.dispatcher.dispatcher_send(f"{DOMAIN}.{RECEIVE_MESSAGE}", packet)
    ^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'helpers'
```

**Comment by thomaskonrad** [comment]
I guess a change like this would be needed: 

https://github.com/rospogrigio/localtuya/commit/9f4405ab82239036f5008c6a52118b0ce022d112
